import { cacheTimes } from '@/lib/api-cache';
import { queryKeys } from '@/api/query-keys';

export const publicApiContracts = [
  {
    service: 'home.getHomepage',
    method: 'GET',
    endpoint: '/api/v1/public/home',
    purpose: 'Public homepage aggregate.',
    responseShape: 'HomepageResponse',
    mapper: 'mapHomepage',
    queryKey: queryKeys.home.all,
    staleTime: cacheTimes.cms,
  },
  {
    service: 'destinations.getPublicDestinations',
    method: 'GET',
    endpoint: '/api/v1/public/destinations',
    purpose: 'Public active destinations listing.',
    responseShape: 'FeaturedDestinationResponse[]',
    mapper: 'mapDestination',
    queryKey: queryKeys.destinations.all,
    staleTime: cacheTimes.list,
  },
  {
    service: 'experiences.getPublicExperiences',
    method: 'GET',
    endpoint: '/api/v1/public/experiences',
    purpose: 'Public active experiences listing.',
    responseShape: 'LuxuryExperienceResponse[]',
    mapper: 'mapExperience',
    queryKey: queryKeys.experiences.all,
    staleTime: cacheTimes.list,
  },
  {
    service: 'about.getAboutPage',
    method: 'GET',
    endpoint: '/api/v1/public/about',
    purpose: 'Public About page aggregate.',
    responseShape: 'PublicAboutResponse',
    mapper: 'pending module mapper',
    queryKey: queryKeys.about.all,
    staleTime: cacheTimes.cms,
  },
  {
    service: 'packages.getPublicPackages',
    method: 'GET',
    endpoint: '/api/v1/public/packages',
    purpose: 'Public package listing groups.',
    responseShape: 'PublicPackageListResponse',
    mapper: 'mapPublicPackages',
    queryKey: queryKeys.packages.all,
    staleTime: cacheTimes.list,
  },
  {
    service: 'packages.getPublicPackageBySlug',
    method: 'GET',
    endpoint: '/api/v1/public/packages/{slug}',
    purpose: 'Public package detail by slug.',
    responseShape: 'LuxuryPackageDetailResponse',
    mapper: 'pending detail mapper',
    queryKey: 'queryKeys.packages.detail(slug)',
    staleTime: cacheTimes.detail,
  },
  {
    service: 'gallery.getPublicGallery',
    method: 'GET',
    endpoint: '/api/v1/public/gallery',
    purpose: 'Public gallery aggregate.',
    responseShape: 'PublicGalleryResponse',
    mapper: 'pending module mapper',
    queryKey: queryKeys.gallery.all,
    staleTime: cacheTimes.list,
  },
  {
    service: 'gallery.getPublicGalleryAlbums',
    method: 'GET',
    endpoint: '/api/v1/public/gallery/albums',
    purpose: 'Public active gallery albums.',
    responseShape: 'GalleryAlbumResponse[]',
    mapper: 'pending module mapper',
    queryKey: queryKeys.gallery.albums,
    staleTime: cacheTimes.list,
  },
  {
    service: 'gallery.getPublicGalleryAlbumBySlug',
    method: 'GET',
    endpoint: '/api/v1/public/gallery/albums/{slug}',
    purpose: 'Public gallery album detail by slug.',
    responseShape: 'GalleryAlbumDetailResponse',
    mapper: 'pending detail mapper',
    queryKey: 'queryKeys.gallery.albumDetail(slug)',
    staleTime: cacheTimes.detail,
  },
  {
    service: 'blog.getPublicBlog',
    method: 'GET',
    endpoint: '/api/v1/public/blog',
    purpose: 'Public blog/journal aggregate.',
    responseShape: 'PublicBlogResponse',
    mapper: 'pending module mapper',
    queryKey: queryKeys.blog.all,
    staleTime: cacheTimes.list,
  },
  {
    service: 'blog.getPublicBlogArticleBySlug',
    method: 'GET',
    endpoint: '/api/v1/public/blog/{slug}',
    purpose: 'Public blog article detail by slug.',
    responseShape: 'ArticleDetailResponse',
    mapper: 'pending detail mapper',
    queryKey: 'queryKeys.blog.detail(slug)',
    staleTime: cacheTimes.detail,
  },
  {
    service: 'blog.getPublicBlogArticlesByCategory',
    method: 'GET',
    endpoint: '/api/v1/public/blog/categories/{slug}',
    purpose: 'Public blog articles by category slug.',
    responseShape: 'ArticleResponse[]',
    mapper: 'pending list mapper',
    queryKey: 'queryKeys.blog.category(slug)',
    staleTime: cacheTimes.list,
  },
  {
    service: 'blog.getPublicBlogArticlesByTag',
    method: 'GET',
    endpoint: '/api/v1/public/blog/tags/{slug}',
    purpose: 'Public blog articles by tag slug.',
    responseShape: 'ArticleResponse[]',
    mapper: 'pending list mapper',
    queryKey: 'queryKeys.blog.tag(slug)',
    staleTime: cacheTimes.list,
  },
  {
    service: 'testimonials.getPublicTestimonials',
    method: 'GET',
    endpoint: '/api/v1/public/testimonials',
    purpose: 'Public testimonial aggregate.',
    responseShape: 'PublicTestimonialResponse',
    mapper: 'pending module mapper',
    queryKey: queryKeys.testimonials.all,
    staleTime: cacheTimes.list,
  },
  {
    service: 'forms.createContactInquiry',
    method: 'POST',
    endpoint: '/api/v1/crm/inquiries',
    purpose: 'Public contact form submission.',
    responseShape: 'ContactInquiryResponse',
    mapper: 'form payload mapper needed at page integration',
    queryKey: null,
    staleTime: cacheTimes.forms,
  },
  {
    service: 'forms.createJourneyRequest',
    method: 'POST',
    endpoint: '/api/v1/crm/journey-requests',
    purpose: 'Public Plan My Journey form submission.',
    responseShape: 'JourneyRequestResponse',
    mapper: 'form payload mapper needed at page integration',
    queryKey: null,
    staleTime: cacheTimes.forms,
  },
  {
    service: 'forms.subscribeToNewsletter',
    method: 'POST',
    endpoint: '/api/v1/crm/newsletter',
    purpose: 'Public newsletter subscription.',
    responseShape: 'NewsletterSubscriberResponse',
    mapper: 'form payload mapper needed at component integration',
    queryKey: null,
    staleTime: cacheTimes.forms,
  },
  {
    service: 'global.getActiveNavigation',
    method: 'GET',
    endpoint: '/api/v1/navigation/active',
    purpose: 'Public active navigation tree.',
    responseShape: 'NavigationResponse[]',
    mapper: 'pending global mapper',
    queryKey: queryKeys.global.navigation,
    staleTime: cacheTimes.cms,
  },
  {
    service: 'seo.getRobotsText',
    method: 'GET',
    endpoint: '/robots.txt',
    purpose: 'Public robots.txt content.',
    responseShape: 'text/plain',
    mapper: 'none',
    queryKey: queryKeys.seo.robots,
    staleTime: cacheTimes.cms,
  },
];
