"""add_home_cms_tables

Revision ID: 414d59e18179
Revises: 0001
Create Date: 2026-08-03 22:42:21.231182
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414d59e18179'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_categories'))
    )
    op.create_index(op.f('ix_blog_categories_id'), 'blog_categories', ['id'], unique=False)
    op.create_index(op.f('ix_blog_categories_slug'), 'blog_categories', ['slug'], unique=True)
    op.create_table('blog_tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_tags'))
    )
    op.create_index(op.f('ix_blog_tags_id'), 'blog_tags', ['id'], unique=False)
    op.create_index(op.f('ix_blog_tags_slug'), 'blog_tags', ['slug'], unique=True)
    op.create_table('company_faqs',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_faqs'))
    )
    op.create_index(op.f('ix_company_faqs_id'), 'company_faqs', ['id'], unique=False)
    op.create_table('company_statistics',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('suffix', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_statistics'))
    )
    op.create_index(op.f('ix_company_statistics_id'), 'company_statistics', ['id'], unique=False)
    op.create_table('contact_settings',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('working_hours', sa.String(length=500), nullable=True),
    sa.Column('google_map_url', sa.String(length=1024), nullable=True),
    sa.Column('emergency_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_settings'))
    )
    op.create_index(op.f('ix_contact_settings_id'), 'contact_settings', ['id'], unique=False)
    op.create_table('core_values',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_values'))
    )
    op.create_index(op.f('ix_core_values_id'), 'core_values', ['id'], unique=False)
    op.create_table('footer_sections',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_footer_sections'))
    )
    op.create_index(op.f('ix_footer_sections_id'), 'footer_sections', ['id'], unique=False)
    op.create_table('gallery_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gallery_categories'))
    )
    op.create_index(op.f('ix_gallery_categories_id'), 'gallery_categories', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_categories_slug'), 'gallery_categories', ['slug'], unique=True)
    op.create_table('navigations',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['navigations.id'], name=op.f('fk_navigations_parent_id_navigations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_navigations'))
    )
    op.create_index(op.f('ix_navigations_id'), 'navigations', ['id'], unique=False)
    op.create_index(op.f('ix_navigations_order'), 'navigations', ['order'], unique=False)
    op.create_index(op.f('ix_navigations_slug'), 'navigations', ['slug'], unique=True)
    op.create_table('package_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_categories'))
    )
    op.create_index(op.f('ix_package_categories_id'), 'package_categories', ['id'], unique=False)
    op.create_index(op.f('ix_package_categories_slug'), 'package_categories', ['slug'], unique=True)
    op.create_table('statistics',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('suffix', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics'))
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    op.create_table('testimonial_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonial_categories'))
    )
    op.create_index(op.f('ix_testimonial_categories_id'), 'testimonial_categories', ['id'], unique=False)
    op.create_index(op.f('ix_testimonial_categories_slug'), 'testimonial_categories', ['slug'], unique=True)
    op.create_table('about_page',
    sa.Column('hero_title', sa.String(length=255), nullable=False),
    sa.Column('hero_subtitle', sa.String(length=500), nullable=True),
    sa.Column('hero_image_id', sa.UUID(), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('our_story', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hero_image_id'], ['media.id'], name=op.f('fk_about_page_hero_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_about_page'))
    )
    op.create_index(op.f('ix_about_page_id'), 'about_page', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('featured_image_id', sa.UUID(), nullable=True),
    sa.Column('banner_image_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('homepage_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_comments', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banner_image_id'], ['media.id'], name=op.f('fk_articles_banner_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], name=op.f('fk_articles_category_id_blog_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['featured_image_id'], ['media.id'], name=op.f('fk_articles_featured_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    op.create_index(op.f('ix_articles_category_id'), 'articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_articles_homepage_featured'), 'articles', ['homepage_featured'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_is_featured'), 'articles', ['is_featured'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_table('awards',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('award_date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('fk_awards_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awards'))
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_table('company_timelines',
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('fk_company_timelines_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_timelines'))
    )
    op.create_index(op.f('ix_company_timelines_id'), 'company_timelines', ['id'], unique=False)
    op.create_table('cta_settings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('button_text', sa.String(length=255), nullable=False),
    sa.Column('button_url', sa.String(length=1024), nullable=False),
    sa.Column('background_image_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['background_image_id'], ['media.id'], name=op.f('fk_cta_settings_background_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cta_settings'))
    )
    op.create_index(op.f('ix_cta_settings_id'), 'cta_settings', ['id'], unique=False)
    op.create_table('featured_destinations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('button_text', sa.String(length=255), nullable=True),
    sa.Column('button_url', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('fk_featured_destinations_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_featured_destinations'))
    )
    op.create_index(op.f('ix_featured_destinations_id'), 'featured_destinations', ['id'], unique=False)
    op.create_index(op.f('ix_featured_destinations_slug'), 'featured_destinations', ['slug'], unique=True)
    op.create_table('footer_links',
    sa.Column('footer_section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['footer_section_id'], ['footer_sections.id'], name=op.f('fk_footer_links_footer_section_id_footer_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_footer_links'))
    )
    op.create_index(op.f('ix_footer_links_footer_section_id'), 'footer_links', ['footer_section_id'], unique=False)
    op.create_index(op.f('ix_footer_links_id'), 'footer_links', ['id'], unique=False)
    op.create_table('gallery_albums',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_media_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('homepage_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gallery_categories.id'], name=op.f('fk_gallery_albums_category_id_gallery_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], name=op.f('fk_gallery_albums_cover_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gallery_albums'))
    )
    op.create_index(op.f('ix_gallery_albums_category_id'), 'gallery_albums', ['category_id'], unique=False)
    op.create_index(op.f('ix_gallery_albums_featured'), 'gallery_albums', ['featured'], unique=False)
    op.create_index(op.f('ix_gallery_albums_homepage_featured'), 'gallery_albums', ['homepage_featured'], unique=False)
    op.create_index(op.f('ix_gallery_albums_id'), 'gallery_albums', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_albums_slug'), 'gallery_albums', ['slug'], unique=True)
    op.create_table('hero_sections',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('button_text', sa.String(length=255), nullable=True),
    sa.Column('button_url', sa.String(length=1024), nullable=True),
    sa.Column('secondary_button_text', sa.String(length=255), nullable=True),
    sa.Column('secondary_button_url', sa.String(length=1024), nullable=True),
    sa.Column('background_image_id', sa.UUID(), nullable=True),
    sa.Column('mobile_background_image_id', sa.UUID(), nullable=True),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('overlay_opacity', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['background_image_id'], ['media.id'], name=op.f('fk_hero_sections_background_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mobile_background_image_id'], ['media.id'], name=op.f('fk_hero_sections_mobile_background_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['media.id'], name=op.f('fk_hero_sections_video_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hero_sections'))
    )
    op.create_index(op.f('ix_hero_sections_id'), 'hero_sections', ['id'], unique=False)
    op.create_table('leadership_members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_id', sa.UUID(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('twitter_url', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_image_id'], ['media.id'], name=op.f('fk_leadership_members_profile_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leadership_members'))
    )
    op.create_index(op.f('ix_leadership_members_id'), 'leadership_members', ['id'], unique=False)
    op.create_table('luxury_collections',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('button_text', sa.String(length=255), nullable=True),
    sa.Column('button_url', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('fk_luxury_collections_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_luxury_collections'))
    )
    op.create_index(op.f('ix_luxury_collections_id'), 'luxury_collections', ['id'], unique=False)
    op.create_index(op.f('ix_luxury_collections_slug'), 'luxury_collections', ['slug'], unique=True)
    op.create_table('luxury_experiences',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('button_text', sa.String(length=255), nullable=True),
    sa.Column('button_url', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('fk_luxury_experiences_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_luxury_experiences'))
    )
    op.create_index(op.f('ix_luxury_experiences_id'), 'luxury_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_luxury_experiences_slug'), 'luxury_experiences', ['slug'], unique=True)
    op.create_table('luxury_packages',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('starting_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('featured_image_id', sa.UUID(), nullable=True),
    sa.Column('banner_image_id', sa.UUID(), nullable=True),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_popular', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banner_image_id'], ['media.id'], name=op.f('fk_luxury_packages_banner_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['package_categories.id'], name=op.f('fk_luxury_packages_category_id_package_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['featured_image_id'], ['media.id'], name=op.f('fk_luxury_packages_featured_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['media.id'], name=op.f('fk_luxury_packages_video_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_luxury_packages'))
    )
    op.create_index(op.f('ix_luxury_packages_category_id'), 'luxury_packages', ['category_id'], unique=False)
    op.create_index(op.f('ix_luxury_packages_city'), 'luxury_packages', ['city'], unique=False)
    op.create_index(op.f('ix_luxury_packages_country'), 'luxury_packages', ['country'], unique=False)
    op.create_index(op.f('ix_luxury_packages_id'), 'luxury_packages', ['id'], unique=False)
    op.create_index(op.f('ix_luxury_packages_is_featured'), 'luxury_packages', ['is_featured'], unique=False)
    op.create_index(op.f('ix_luxury_packages_is_popular'), 'luxury_packages', ['is_popular'], unique=False)
    op.create_index(op.f('ix_luxury_packages_slug'), 'luxury_packages', ['slug'], unique=True)
    op.create_table('partners',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('logo_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logo_id'], ['media.id'], name=op.f('fk_partners_logo_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_table('seo_settings',
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('robots', sa.String(length=255), nullable=False),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image_id', sa.UUID(), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=False),
    sa.Column('twitter_title', sa.String(length=255), nullable=True),
    sa.Column('twitter_description', sa.Text(), nullable=True),
    sa.Column('twitter_image_id', sa.UUID(), nullable=True),
    sa.Column('schema_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['og_image_id'], ['media.id'], name=op.f('fk_seo_settings_og_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['twitter_image_id'], ['media.id'], name=op.f('fk_seo_settings_twitter_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_settings'))
    )
    op.create_index(op.f('ix_seo_settings_id'), 'seo_settings', ['id'], unique=False)
    op.create_table('site_settings',
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('logo_id', sa.UUID(), nullable=True),
    sa.Column('favicon_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('google_map_url', sa.String(length=1024), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('analytics_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['favicon_id'], ['media.id'], name=op.f('fk_site_settings_favicon_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logo_id'], ['media.id'], name=op.f('fk_site_settings_logo_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    op.create_table('why_choose_us',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('fk_why_choose_us_image_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_why_choose_us'))
    )
    op.create_index(op.f('ix_why_choose_us_id'), 'why_choose_us', ['id'], unique=False)
    op.create_table('article_gallery',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_gallery_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_article_gallery_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_gallery'))
    )
    op.create_index(op.f('ix_article_gallery_article_id'), 'article_gallery', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_gallery_id'), 'article_gallery', ['id'], unique=False)
    op.create_table('article_tags',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_tags_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], name=op.f('fk_article_tags_tag_id_blog_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_tags'))
    )
    op.create_index(op.f('ix_article_tags_article_id'), 'article_tags', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tags_id'), 'article_tags', ['id'], unique=False)
    op.create_index(op.f('ix_article_tags_tag_id'), 'article_tags', ['tag_id'], unique=False)
    op.create_table('gallery_items',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], name=op.f('fk_gallery_items_album_id_gallery_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_gallery_items_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gallery_items'))
    )
    op.create_index(op.f('ix_gallery_items_album_id'), 'gallery_items', ['album_id'], unique=False)
    op.create_index(op.f('ix_gallery_items_id'), 'gallery_items', ['id'], unique=False)
    op.create_table('package_exclusions',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_package_exclusions_package_id_luxury_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_exclusions'))
    )
    op.create_index(op.f('ix_package_exclusions_id'), 'package_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_package_exclusions_package_id'), 'package_exclusions', ['package_id'], unique=False)
    op.create_table('package_faqs',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_package_faqs_package_id_luxury_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_faqs'))
    )
    op.create_index(op.f('ix_package_faqs_id'), 'package_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_package_faqs_package_id'), 'package_faqs', ['package_id'], unique=False)
    op.create_table('package_gallery',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_package_gallery_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_package_gallery_package_id_luxury_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_gallery'))
    )
    op.create_index(op.f('ix_package_gallery_id'), 'package_gallery', ['id'], unique=False)
    op.create_index(op.f('ix_package_gallery_package_id'), 'package_gallery', ['package_id'], unique=False)
    op.create_table('package_highlights',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_package_highlights_package_id_luxury_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_highlights'))
    )
    op.create_index(op.f('ix_package_highlights_id'), 'package_highlights', ['id'], unique=False)
    op.create_index(op.f('ix_package_highlights_package_id'), 'package_highlights', ['package_id'], unique=False)
    op.create_table('package_inclusions',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_package_inclusions_package_id_luxury_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_inclusions'))
    )
    op.create_index(op.f('ix_package_inclusions_id'), 'package_inclusions', ['id'], unique=False)
    op.create_index(op.f('ix_package_inclusions_package_id'), 'package_inclusions', ['package_id'], unique=False)
    op.create_table('package_itineraries',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hotel', sa.String(length=255), nullable=True),
    sa.Column('meal_plan', sa.String(length=255), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_package_itineraries_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_package_itineraries_package_id_luxury_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_itineraries'))
    )
    op.create_index(op.f('ix_package_itineraries_id'), 'package_itineraries', ['id'], unique=False)
    op.create_index(op.f('ix_package_itineraries_package_id'), 'package_itineraries', ['package_id'], unique=False)
    op.create_table('related_articles',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('related_article_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_related_articles_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_article_id'], ['articles.id'], name=op.f('fk_related_articles_related_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_related_articles'))
    )
    op.create_index(op.f('ix_related_articles_article_id'), 'related_articles', ['article_id'], unique=False)
    op.create_index(op.f('ix_related_articles_id'), 'related_articles', ['id'], unique=False)
    op.create_table('testimonials',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('destination_slug', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_location', sa.String(length=255), nullable=True),
    sa.Column('customer_designation', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('profile_image_id', sa.UUID(), nullable=True),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('travel_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('homepage_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['testimonial_categories.id'], name=op.f('fk_testimonials_category_id_testimonial_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['luxury_packages.id'], name=op.f('fk_testimonials_package_id_luxury_packages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_image_id'], ['media.id'], name=op.f('fk_testimonials_profile_image_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['media.id'], name=op.f('fk_testimonials_video_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonials'))
    )
    op.create_index(op.f('ix_testimonials_category_id'), 'testimonials', ['category_id'], unique=False)
    op.create_index(op.f('ix_testimonials_destination_slug'), 'testimonials', ['destination_slug'], unique=False)
    op.create_index(op.f('ix_testimonials_homepage_featured'), 'testimonials', ['homepage_featured'], unique=False)
    op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
    op.create_index(op.f('ix_testimonials_is_featured'), 'testimonials', ['is_featured'], unique=False)
    op.create_index(op.f('ix_testimonials_package_id'), 'testimonials', ['package_id'], unique=False)
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_admin_users_email', 'admin_users', type_='unique')
    op.add_column('media', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('media', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('media', 'media_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_media_is_deleted'), 'media', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_is_deleted'), table_name='media')
    op.alter_column('media', 'media_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'image'::character varying"),
               existing_nullable=False)
    op.drop_column('media', 'deleted_at')
    op.drop_column('media', 'is_deleted')
    op.create_unique_constraint('uq_admin_users_email', 'admin_users', ['email'])
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'editor'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_testimonials_package_id'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_featured'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_homepage_featured'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_destination_slug'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_category_id'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_related_articles_id'), table_name='related_articles')
    op.drop_index(op.f('ix_related_articles_article_id'), table_name='related_articles')
    op.drop_table('related_articles')
    op.drop_index(op.f('ix_package_itineraries_package_id'), table_name='package_itineraries')
    op.drop_index(op.f('ix_package_itineraries_id'), table_name='package_itineraries')
    op.drop_table('package_itineraries')
    op.drop_index(op.f('ix_package_inclusions_package_id'), table_name='package_inclusions')
    op.drop_index(op.f('ix_package_inclusions_id'), table_name='package_inclusions')
    op.drop_table('package_inclusions')
    op.drop_index(op.f('ix_package_highlights_package_id'), table_name='package_highlights')
    op.drop_index(op.f('ix_package_highlights_id'), table_name='package_highlights')
    op.drop_table('package_highlights')
    op.drop_index(op.f('ix_package_gallery_package_id'), table_name='package_gallery')
    op.drop_index(op.f('ix_package_gallery_id'), table_name='package_gallery')
    op.drop_table('package_gallery')
    op.drop_index(op.f('ix_package_faqs_package_id'), table_name='package_faqs')
    op.drop_index(op.f('ix_package_faqs_id'), table_name='package_faqs')
    op.drop_table('package_faqs')
    op.drop_index(op.f('ix_package_exclusions_package_id'), table_name='package_exclusions')
    op.drop_index(op.f('ix_package_exclusions_id'), table_name='package_exclusions')
    op.drop_table('package_exclusions')
    op.drop_index(op.f('ix_gallery_items_id'), table_name='gallery_items')
    op.drop_index(op.f('ix_gallery_items_album_id'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_index(op.f('ix_article_tags_tag_id'), table_name='article_tags')
    op.drop_index(op.f('ix_article_tags_id'), table_name='article_tags')
    op.drop_index(op.f('ix_article_tags_article_id'), table_name='article_tags')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_article_gallery_id'), table_name='article_gallery')
    op.drop_index(op.f('ix_article_gallery_article_id'), table_name='article_gallery')
    op.drop_table('article_gallery')
    op.drop_index(op.f('ix_why_choose_us_id'), table_name='why_choose_us')
    op.drop_table('why_choose_us')
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_seo_settings_id'), table_name='seo_settings')
    op.drop_table('seo_settings')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_luxury_packages_slug'), table_name='luxury_packages')
    op.drop_index(op.f('ix_luxury_packages_is_popular'), table_name='luxury_packages')
    op.drop_index(op.f('ix_luxury_packages_is_featured'), table_name='luxury_packages')
    op.drop_index(op.f('ix_luxury_packages_id'), table_name='luxury_packages')
    op.drop_index(op.f('ix_luxury_packages_country'), table_name='luxury_packages')
    op.drop_index(op.f('ix_luxury_packages_city'), table_name='luxury_packages')
    op.drop_index(op.f('ix_luxury_packages_category_id'), table_name='luxury_packages')
    op.drop_table('luxury_packages')
    op.drop_index(op.f('ix_luxury_experiences_slug'), table_name='luxury_experiences')
    op.drop_index(op.f('ix_luxury_experiences_id'), table_name='luxury_experiences')
    op.drop_table('luxury_experiences')
    op.drop_index(op.f('ix_luxury_collections_slug'), table_name='luxury_collections')
    op.drop_index(op.f('ix_luxury_collections_id'), table_name='luxury_collections')
    op.drop_table('luxury_collections')
    op.drop_index(op.f('ix_leadership_members_id'), table_name='leadership_members')
    op.drop_table('leadership_members')
    op.drop_index(op.f('ix_hero_sections_id'), table_name='hero_sections')
    op.drop_table('hero_sections')
    op.drop_index(op.f('ix_gallery_albums_slug'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_id'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_homepage_featured'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_featured'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_category_id'), table_name='gallery_albums')
    op.drop_table('gallery_albums')
    op.drop_index(op.f('ix_footer_links_id'), table_name='footer_links')
    op.drop_index(op.f('ix_footer_links_footer_section_id'), table_name='footer_links')
    op.drop_table('footer_links')
    op.drop_index(op.f('ix_featured_destinations_slug'), table_name='featured_destinations')
    op.drop_index(op.f('ix_featured_destinations_id'), table_name='featured_destinations')
    op.drop_table('featured_destinations')
    op.drop_index(op.f('ix_cta_settings_id'), table_name='cta_settings')
    op.drop_table('cta_settings')
    op.drop_index(op.f('ix_company_timelines_id'), table_name='company_timelines')
    op.drop_table('company_timelines')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_featured'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_homepage_featured'), table_name='articles')
    op.drop_index(op.f('ix_articles_category_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_about_page_id'), table_name='about_page')
    op.drop_table('about_page')
    op.drop_index(op.f('ix_testimonial_categories_slug'), table_name='testimonial_categories')
    op.drop_index(op.f('ix_testimonial_categories_id'), table_name='testimonial_categories')
    op.drop_table('testimonial_categories')
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_package_categories_slug'), table_name='package_categories')
    op.drop_index(op.f('ix_package_categories_id'), table_name='package_categories')
    op.drop_table('package_categories')
    op.drop_index(op.f('ix_navigations_slug'), table_name='navigations')
    op.drop_index(op.f('ix_navigations_order'), table_name='navigations')
    op.drop_index(op.f('ix_navigations_id'), table_name='navigations')
    op.drop_table('navigations')
    op.drop_index(op.f('ix_gallery_categories_slug'), table_name='gallery_categories')
    op.drop_index(op.f('ix_gallery_categories_id'), table_name='gallery_categories')
    op.drop_table('gallery_categories')
    op.drop_index(op.f('ix_footer_sections_id'), table_name='footer_sections')
    op.drop_table('footer_sections')
    op.drop_index(op.f('ix_core_values_id'), table_name='core_values')
    op.drop_table('core_values')
    op.drop_index(op.f('ix_contact_settings_id'), table_name='contact_settings')
    op.drop_table('contact_settings')
    op.drop_index(op.f('ix_company_statistics_id'), table_name='company_statistics')
    op.drop_table('company_statistics')
    op.drop_index(op.f('ix_company_faqs_id'), table_name='company_faqs')
    op.drop_table('company_faqs')
    op.drop_index(op.f('ix_blog_tags_slug'), table_name='blog_tags')
    op.drop_index(op.f('ix_blog_tags_id'), table_name='blog_tags')
    op.drop_table('blog_tags')
    op.drop_index(op.f('ix_blog_categories_slug'), table_name='blog_categories')
    op.drop_index(op.f('ix_blog_categories_id'), table_name='blog_categories')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###