"""create_seo_tables

Revision ID: 9a8b7c6d5e4f
Revises: f7cb15dc2227
Create Date: 2026-08-07 23:31:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, NUMERIC


# revision identifiers, used by Alembic.
revision: str = '9a8b7c6d5e4f'
down_revision: Union[str, None] = 'f7cb15dc2227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create seo_settings table (if not exists)
    conn = op.get_bind()
    
    if not conn.dialect.has_table(conn, 'seo_settings'):
        op.create_table(
            'seo_settings',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('site_name', sa.String(length=255), nullable=True),
            sa.Column('website_url', sa.String(length=1024), nullable=True),
            sa.Column('default_meta_title', sa.String(length=255), nullable=True),
            sa.Column('default_meta_description', sa.Text(), nullable=True),
            sa.Column('default_keywords', sa.Text(), nullable=True),
            sa.Column('canonical_url', sa.String(length=1024), nullable=True),
            sa.Column('default_robots', sa.String(length=255), server_default='index, follow', nullable=False),
            sa.Column('organization_name', sa.String(length=255), nullable=True),
            sa.Column('organization_logo_id', UUID(as_uuid=True), sa.ForeignKey('media.id', ondelete='SET NULL'), nullable=True),
            sa.Column('default_og_image_id', UUID(as_uuid=True), sa.ForeignKey('media.id', ondelete='SET NULL'), nullable=True),
            sa.Column('default_twitter_image_id', UUID(as_uuid=True), sa.ForeignKey('media.id', ondelete='SET NULL'), nullable=True),
            sa.Column('twitter_card', sa.String(length=50), server_default='summary_large_image', nullable=False),
            sa.Column('facebook_app_id', sa.String(length=255), nullable=True),
            sa.Column('google_site_verification', sa.String(length=255), nullable=True),
            sa.Column('bing_site_verification', sa.String(length=255), nullable=True),
            sa.Column('pinterest_verification', sa.String(length=255), nullable=True),
            sa.Column('theme_color', sa.String(length=7), nullable=True),
            sa.Column('schema_json', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_settings'))
        )
        with op.batch_alter_table('seo_settings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_seo_settings_id'), ['id'], unique=False)
    
    # Create page_seo table (if not exists)
    if not conn.dialect.has_table(conn, 'page_seo'):
        op.create_table(
            'page_seo',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('page_key', sa.String(length=255), nullable=False),
            sa.Column('meta_title', sa.String(length=255), nullable=True),
            sa.Column('meta_description', sa.Text(), nullable=True),
            sa.Column('keywords', sa.Text(), nullable=True),
            sa.Column('canonical_url', sa.String(length=1024), nullable=True),
            sa.Column('slug', sa.String(length=1024), nullable=True),
            sa.Column('og_title', sa.String(length=255), nullable=True),
            sa.Column('og_description', sa.Text(), nullable=True),
            sa.Column('og_image_id', UUID(as_uuid=True), sa.ForeignKey('media.id', ondelete='SET NULL'), nullable=True),
            sa.Column('twitter_title', sa.String(length=255), nullable=True),
            sa.Column('twitter_description', sa.Text(), nullable=True),
            sa.Column('twitter_image_id', UUID(as_uuid=True), sa.ForeignKey('media.id', ondelete='SET NULL'), nullable=True),
            sa.Column('robots', sa.String(length=255), nullable=True),
            sa.Column('schema_json', sa.Text(), nullable=True),
            sa.Column('priority', NUMERIC(2, 1), nullable=True),
            sa.Column('change_frequency', sa.String(length=50), nullable=True),
            sa.Column('include_in_sitemap', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_page_seo'))
        )
        with op.batch_alter_table('page_seo', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_page_seo_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_page_seo_page_key'), ['page_key'], unique=True)
    
    # Create sitemap_settings table (if not exists)
    if not conn.dialect.has_table(conn, 'sitemap_settings'):
        op.create_table(
            'sitemap_settings',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('include_pages', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('include_blog', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('include_destinations', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('include_experiences', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('include_packages', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('include_gallery', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('default_priority', NUMERIC(2, 1), server_default='0.5', nullable=False),
            sa.Column('default_change_frequency', sa.String(length=50), server_default='weekly', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_sitemap_settings'))
        )
        with op.batch_alter_table('sitemap_settings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_sitemap_settings_id'), ['id'], unique=False)
    
    # Create robots_settings table (if not exists)
    if not conn.dialect.has_table(conn, 'robots_settings'):
        op.create_table(
            'robots_settings',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('robots_content', sa.Text(), server_default='User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\n\nSitemap: https://example.com/sitemap.xml', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_robots_settings'))
        )
        with op.batch_alter_table('robots_settings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_robots_settings_id'), ['id'], unique=False)
    
    # Create redirects table (if not exists)
    if not conn.dialect.has_table(conn, 'redirects'):
        op.create_table(
            'redirects',
            sa.Column('id', UUID(), nullable=False),
            sa.Column('source_path', sa.String(length=1024), nullable=False),
            sa.Column('destination_path', sa.String(length=1024), nullable=False),
            sa.Column('redirect_type', sa.Integer(), server_default='301', nullable=False),
            sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_redirects'))
        )
        with op.batch_alter_table('redirects', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_redirects_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_redirects_source_path'), ['source_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirects_source_path'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_robots_settings_id'), table_name='robots_settings')
    op.drop_table('robots_settings')
    op.drop_index(op.f('ix_sitemap_settings_id'), table_name='sitemap_settings')
    op.drop_table('sitemap_settings')
    op.drop_index(op.f('ix_page_seo_page_key'), table_name='page_seo')
    op.drop_index(op.f('ix_page_seo_id'), table_name='page_seo')
    op.drop_table('page_seo')
    op.drop_index(op.f('ix_seo_settings_id'), table_name='seo_settings')
    op.drop_table('seo_settings')
    # ### end Alembic commands ###