"""add_crm_tables

Revision ID: f7cb15dc2227
Revises: a8c7f4d2b901
Create Date: 2026-08-07 22:36:31.147543
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cb15dc2227'
down_revision: Union[str, None] = 'a8c7f4d2b901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_inquiries'))
    )
    op.create_index(op.f('ix_contact_inquiries_email'), 'contact_inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_contact_inquiries_id'), 'contact_inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_contact_inquiries_status'), 'contact_inquiries', ['status'], unique=False)
    op.create_table('journey_requests',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('travel_date', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('travelers', sa.Integer(), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('travel_style', sa.String(length=255), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_requests'))
    )
    op.create_index(op.f('ix_journey_requests_email'), 'journey_requests', ['email'], unique=False)
    op.create_index(op.f('ix_journey_requests_id'), 'journey_requests', ['id'], unique=False)
    op.create_index(op.f('ix_journey_requests_status'), 'journey_requests', ['status'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_subscribers'))
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_subscribers_is_active'), 'newsletter_subscribers', ['is_active'], unique=False)
    op.alter_column('contact_page_cms', 'hero_overlay_opacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='Overlay opacity (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('contact_page_cms', 'default_map_zoom',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_comment='Default Google Maps zoom level (1-20)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_page_cms', 'default_map_zoom',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'15'::character varying"),
               existing_comment='Default Google Maps zoom level (1-20)',
               existing_nullable=False)
    op.alter_column('contact_page_cms', 'hero_overlay_opacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_comment='Overlay opacity (0.0-1.0)',
               existing_nullable=False)
    op.drop_index(op.f('ix_newsletter_subscribers_is_active'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_journey_requests_status'), table_name='journey_requests')
    op.drop_index(op.f('ix_journey_requests_id'), table_name='journey_requests')
    op.drop_index(op.f('ix_journey_requests_email'), table_name='journey_requests')
    op.drop_table('journey_requests')
    op.drop_index(op.f('ix_contact_inquiries_status'), table_name='contact_inquiries')
    op.drop_index(op.f('ix_contact_inquiries_id'), table_name='contact_inquiries')
    op.drop_index(op.f('ix_contact_inquiries_email'), table_name='contact_inquiries')
    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###